### ISSUE TITLE
[Deployment] Crontab guest map destruction

### ISSUE THREAD

**Issue by andneuma** [magdalena19/ratMap#487]
Setup `delete_expired_guest_maps` as cronjob

```
crontab -e
0 4 * * 7 cd /home/korner/lberg-map; ./bin/bundle exec rake delete_expired_guest_maps
```

**Comment by pr0totyp** [comment]
0 4 * * 7 docker-compose exec  ratmap bash -c "/ratmap/bin/bundle exec rake delete_expired_guest_maps"
