### ISSUE TITLE
Finalize backup strategy

### ISSUE THREAD

**Issue by pr0totyp** [magdalena19/ratMap#516]
Backup is still half brocken. where to copy dumps?

**Comment by andneuma** [comment]
Vielleicht sollten wir die Szenarien, vor denen wir uns mit Backups schützen wollen mal skizzieren, mir ist das noch nicht ganz schlüssig alles. In-Berlin macht ja seine eigenen Backups, von daher wäre die Frage, ob du das auf nen zweiten Storage quasi-redundant dumpen willst. Dafür wäre ja zB die Instanz von @kjoscha eine Option
