### ISSUE TITLE
Create Debian package

### ISSUE THREAD

**Issue by pr0totyp** [magdalena19/ratMap#517]
capsulated the ruby app inito an deb pkt with global config file in /etc

**Comment by andneuma** [comment]
Ich persönlich finde, dass das nicht unbedingt Teil des Milestones "1.0" sein sollte solang nicht andere Dinge behandelt sind: Logwatch, SSL-Cert-Bot, etc. Spricht für mich überhaupt nichts dagegen (im Gegenteil!) das zu machen nur denke ich kann das auch zu einem späteren Zeitpunkt gemacht werden, da dass ja die Weiterverbreitung der Software betrifft und nicht die Lauffähigkeit unserer SaaS-Instance auf https://maps.coderat.cc

**Comment by andneuma** [comment]
Bzw. vielleicht können wir es auch so machen - will hier auch keinen Enthusiasmus bremsen - dass wir die dringendsten issues mit `CRITICAL` labeln und die priorität behandeln. Wenn dann noch Zeit und Lust ist können wir sowas hier zB ja auch noch machen

**Comment by andneuma** [comment]
Issue gibts schon
